name: deploy-book
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MyST + Jupyter Book
        run: |
          npm install -g mystmd
          pip install -U jupyter-book

      - name: Build book (HTML)
        run: jupyter book build --html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
